### ISSUE TITLE
Drag and Drop selected range instead of dragging handle

### ISSUE THREAD

**Issue by jesusgp22** [zillow/react-slider#101]
I am trying to use [react-slider][1] to build a range selector component that I will later integrate with a chart, my goal is to be able to both drag and drop handles to change the min and max values of the range or to be able to drag the selected range across the range selector, similar to what highcharts does with their range selector (example: [highcharts range selector][2])

  [1]: https://github.com/mpowaga/react-slider/issues "react-slider"
  [2]: http://www.highcharts.com/docs/chart-concepts/range-selector

How would you go about implementing this behaviour?

**Comment by senkevichdv** [comment]
Any news about this behaviour?
