### ISSUE TITLE
React 15.5

### ISSUE THREAD

**Issue by nikitatrifan** [zillow/react-slider#102]
Hi guys, I'm just updated React to v15.5 and it's throwing this error below -

`Warning: ReactSlider: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

Could you fix it please?

**Comment by fluse** [comment]
And

Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by Bjorgvin** [comment]
I noticed the [PR-104](https://github.com/mpowaga/react-slider/pull/104) from @spiderbites, but how prop-types and create-react-class are imported didn't seem to comply with the _spirit_ of the project; Hope it's ok that I added my own [PR-105](https://github.com/mpowaga/react-slider/pull/105)

If this isn't merged soon, @mpowaga, my version can used like `"react-slider": "Bjorgvin/react-slider#master"` in your `package.json`

**Comment by Bjorgvin** [comment]
@mpowaga when can we expect this to be added to a version on npm? Also, I'm looking at [npmjs/react-slider](https://www.npmjs.com/package/react-slider) and it says the latest version is 0.7.0 but the [github/releases](https://github.com/mpowaga/react-slider/releases) shows v0.6.1 as the latest. 

Anyway... would like to have a clean package.json with a simple reference to react-slider `"react-slider": "react-slider"` 

...hopefully soon and thanks for the merge.
