### ISSUE TITLE
Inside variable width container, thumbs go off bar

### ISSUE THREAD

**Issue by odama626** [zillow/react-slider#109]
![image](https://user-images.githubusercontent.com/11347689/27659535-7b2072e8-5c19-11e7-8223-abb55f80aa4c.png)

Setting a thumb to max value by default puts the thumb off the bar until resizing browser window or scrolling.

Only seen in mobile view in chrome and on mobile devices

I think PR#72 would fix this

**Comment by markcorrea** [comment]
<img width="327" alt="Screen Shot 2019-10-16 at 23 42 03" src="https://user-images.githubusercontent.com/12589403/66973513-9518a580-f06e-11e9-8939-e07c2c985696.png">

Having the same issue here. But in my case, no matter the format (desktop, mobile) or if I resize the screen or move the thumbs, if I put it in the max, it will be cut, and only on the right side. I've tried to change the CSS but it's something in the component itself.

Can anyone help me?

**Comment by stonebk** [comment]
@markcorrea what version are you using? Can you provide a repro on https://codesandbox.io/?
