### ISSUE TITLE
onChanged fired twice

### ISSUE THREAD

**Issue by flosse** [zillow/react-slider#11]
My `onChanged` function gets called twice :-\ How can I avoid it?

**Comment by qwtel** [comment]
Oh I almost forgot about this one :/ 
I'll take a look at it.

**Comment by qwtel** [comment]
If you want a quick fix, just remove the click event handler from the slider (line 354). This means the handles can no longer be moved by clicking on the slider, depending on what you want to do this might not be a big deal.
Also note that this issue does not occur on mobile.

**Comment by qwtel** [comment]
Btw: seems to be fixed in the current version
