### ISSUE TITLE
Clicking bar always snaps to max value

### ISSUE THREAD

**Issue by B-Reif** [zillow/react-slider#112]
My slider is always set to the max value on click, no matter where on the bar I click. Resizing the window fixes the issue.

https://giphy.com/gifs/xT39Dn7OvZYUJVYVRS/html5

I suspect this is because the slider is inside of a menu that slides in, so it's in a rather different position than it was at render time.

I'd rather not wait until the menu has slid in to render the slider. Could the slider call _handleResize automatically on clicks? Or could the slider expose _handleResize to the application so we can force a recalc when needed?

You can also recreate this (or similar issues) by mucking around with the slider's sizing/position CSS in the inspector before using it.

**Comment by deadghost** [comment]
Similar issue. Clicking the min-value handle snaps the max-value handle to the max. I'm using an older version though so can't say if it's been resolved since.
