### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive

### ISSUE THREAD

**Issue by jontro** [zillow/react-slider#117]
Chrome gives the following warning when using the latest version of react-slider.
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
e @ react-slider.js:17
_onTouchMove @ react-slider.js:506

**Comment by alex-blair** [comment]
I added the CSS property `touch-action: none;` to my slider style and that stopped the warning. Was suggested here: https://stackoverflow.com/questions/42101723/unable-to-preventdefault-inside-passive-event-listener
