### ISSUE TITLE
Support for react 16

### ISSUE THREAD

**Issue by ghost** [zillow/react-slider#120]
I have the following error. How to fix it?

```Can't resolve 'create-react-class' in```

**Comment by cascornelissen** [comment]
I ran into the same issue and I'm fixing it by installing [`create-react-class`](https://www.npmjs.com/package/create-react-class) manually for now:

```
npm install --save create-react-class
```

**Comment by mpowaga** [comment]
Looks like information about peer dependencies is missing in readme.

**Comment by axelg12** [comment]
#131 Fixes this right?

**Comment by techgyani** [comment]
#131 is not a automatic fix. create-react-class is declared as peer dependency, therefore it is required to install the same manually in the project.

May be in the favour of ES6, this dependency can be dropped in future by @mpowaga.

**Comment by stonebk** [comment]
Fixed with #147
