### ISSUE TITLE
Bug: NaN slider value on mobile after long-press (context menu event)

### ISSUE THREAD

**Issue by benny-medflyt** [zillow/react-slider#128]
This bug can be easily reproduced with the react-slider example: https://mpowaga.github.io/react-slider/

Open It in Chrome, open the "Developer tools" panel. Then turn on mobile device mode ("Toggle device toolbar").

Long press on one of the sliders (aim right in the middle, not near the edges), and then drag it. The value will turn to `NaN`.

![peek 2018-03-12 13-47](https://user-images.githubusercontent.com/24827547/37300416-50ea429e-25fc-11e8-9955-d1a07ca5989a.gif)

**Comment by YoavHortman** [comment]
I had the same issue, very good demonstration btw

**Comment by sebmor** [comment]
The workaround provided is only a patch, it will now just revert to the previous location before it was NaN.
But the behaviour as described on top still exists.

A real solution would be that this just doesn't occur.

**Comment by benny-medflyt** [comment]
@sebmor Can you please elaborate? The fix in #129 was meant to completely solve this issue and as far as I can tell it does

**Comment by sebmor** [comment]
@benny-medflyt  It doesn't. What happens now on mobile is when you hold for a few seconds and then drag, after you let go it will go back to the start position.

If you see in the code https://github.com/mpowaga/react-slider/commit/7a16457678a2e0363e67eceb87b6be57aa811071 all that happened was, if the position is undefined, to go back to the start position.

But the main bug where you hold for a few seconds the position turns to NaN is not solved and is just the same as shown in first post.
