### ISSUE TITLE
Suggested enhancement: Snap-and-drag behavior

### ISSUE THREAD

**Issue by motiz88** [zillow/react-slider#13]
For my needs, the user should be able to click (or touch) anywhere on the slider, have the handle snap to that position, and continue dragging from there without releasing the mouse button (or finger).

Pull request #14 is my suggested implementation. Future work may include a prop to configure the various behaviors (perhaps similar to [noUiSlider](https://github.com/leongersen/noUiSlider)'s `behaviour` option).

**Comment by mpowaga** [comment]
Thanks.
