### ISSUE TITLE
Unable to see slider

### ISSUE THREAD

**Issue by Harshit5295** [zillow/react-slider#130]
I have included everything and my code compiles well but I can't see my slider on browser.

**Comment by mpowaga** [comment]
Make sure you've styled a slider with CSS. Check [index.html](https://github.com/mpowaga/react-slider/blob/master/index.html) to see how to do it.

**Comment by Antonio-Riccelli** [comment]
@Harshit5295 how did you solve this? I have a similar issue, it all compiles and I can see the numeric value but no slider. 
@mpowaga what did you mean by checking the index.html file? 

![image](https://github.com/zillow/react-slider/assets/39813213/90f2a8a5-a691-4763-b47b-2d093c908bc6)
