### ISSUE TITLE
With inverted vertical slider the arrow keys move the slider in the wrong direction

### ISSUE THREAD

**Issue by gauthierm** [zillow/react-slider#143]
I'm making a volume control that is vertical and inverted. When the handle is focused, the arrow keys move the slider the opposite of what is on the screen (down moves up, up moves down).

**Comment by StarNeit** [comment]
Hi @gauthierm 
Did you find reason of issue?

**Comment by gauthierm** [comment]
@StarNeit Yes. The issue is the keyboard handlers do not check `this.props.inverted` before adding or removing values.

**Comment by gauthierm** [comment]
Fixed in https://github.com/mpowaga/react-slider/pull/144

**Comment by stonebk** [comment]
Fixed with #147
