### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by wavesbig** [zillow/react-slider#148]

**Comment by wavesbig** [comment]
## Are there @types packages provided

**Comment by stonebk** [comment]
> ## Are there @types packages provided

Not currently. We do not use typescript in our projects at Zillow, so we don't currently have a need for it. If somebody would like to submit a PR, I'd be happy to review and merge!

**Comment by lenilsonjr** [comment]
fyi: while there's no types for `react-slider`, you can use `//@ts-ignore` right before the module import to use the package without typechecking:

```javascript
//@ts-ignore
import ReactSlider from 'react-slider';
```

**Comment by waynevanson** [comment]
Types are available, but need to be updated and generics added: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-slider

Alternatively, I'd be happy and would prefer to rewrite this in typescript to future proof it.

Which would you prefer @mpowaga?

**Comment by waynevanson** [comment]
I just submitted a thick PR to DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40094

I used the prop types, assuming they're in date.

**Comment by waynevanson** [comment]
@stonebk

**Comment by stonebk** [comment]
@waynevanson, thanks for looking into this! Yes, the prop types should be up to date. Forgive my ignorance, does anything need to happen within this project, or do people just pull the definitions directly from definitelytyped?

**Comment by waynevanson** [comment]
> @waynevanson, thanks for looking into this! Yes, the prop types should be up to date. Forgive my ignorance, does anything need to happen within this project, or do people just pull the definitions directly from definitelytyped?

People pull the definitions by running `yarn add -D @types/react-slider` :)

**Comment by stonebk** [comment]
@waynevanson does this make sense? https://github.com/zillow/react-slider/pull/155

**Comment by waynevanson** [comment]
@stonebk yes it does!

**Comment by waynevanson** [comment]
@stonebk My pull got rejected, so all credit goes to:

+ @jsonunger
+ @bjorgvin
