### ISSUE TITLE
IE9 support ?

### ISSUE THREAD

**Issue by khenlevy** [zillow/react-slider#150]
currently nothing shown when entering :
https://zillow.github.io/react-slider/

No support to Internet Explorer 9.
any plans to support it?

**Comment by stonebk** [comment]
IE9, eeek!

Right now the lowest I'd say we officially support is IE11. I know react-styleguidist has an issue with IE that we are working around in create-react-styleguide. We may need to update create-react-styleguide to get those changes though...

**Comment by stonebk** [comment]
@khenlevy, OK, I updated create-react-styleguide -- the docs should now be working correctly in IE11. Note, this was only an issue with the docs, and not the component.
