### ISSUE TITLE
Ticks not available

### ISSUE THREAD

**Issue by vdhyani-binary** [zillow/react-slider#153]

**Comment by stonebk** [comment]
More information about what you are expecting in terms of an API change would be helpful. I'm assuming you are asking for something along the lines of:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range#Adding_hash_marks_and_labels

**Comment by vdhyani-binary** [comment]
Tick i mean Marks that is the range below slider that option is missing into this library....

**Comment by vdhyani-binary** [comment]
![Capture](https://user-images.githubusercontent.com/58029027/70790550-51ff5800-1dbb-11ea-96ba-c56adbd42dfd.PNG)

**Comment by stonebk** [comment]
How should it handle larger ranges of values where rendering every mark wouldn't fit?

**Comment by vdhyani-binary** [comment]
that is the step which is move with the handle, other library provide the solution with same way

**Comment by vdhyani-binary** [comment]
as in the library we have min max and step props so according to that we can generate the array to show in the scale.
0  1  2   3  4   5........

**Comment by vdhyani-binary** [comment]
as in the library we have min max and step props so according to that we can generate the array to show in the scale.
0 1 2 3 4 5........

but i need dynamic solution..

**Comment by zeeshanjan82** [comment]
@vdhyani-binary where you able to find any solution?
