### ISSUE TITLE
Clicking on track on vertical slider is buggy

### ISSUE THREAD

**Issue by pt8o** [zillow/react-slider#156]
This can be reproduced on the [your demo site itself](https://zillow.github.io/react-slider/).

1. Scroll down to the vertical slider. Click on the track: the nearest thumb should jump to where you clicked
1. Refresh the page (e.g. `cmd+r`). The page should reload already scrolled to the same location.
1. Click the track

Expected:
* nearest thumb should jump to where you clicked

Actual:
* the bottom thumb gets selected, but doesn't move
* you can slide it up and down by moving the cursor, but the cursor and thumb are in different places on the page
* clicking on the track again will jump the bottom thumb to the bottom of the slider

Tested on Linux and Mac using the latest Firefox and Chrome.

If you scroll to the top of the page again and then reload, it works again! So this bug only seems to happen if you **refresh the page while scrolled down**.

![output](https://user-images.githubusercontent.com/22176050/71910277-99b99b00-313f-11ea-9d2f-c25700687fe3.gif)

**Comment by stonebk** [comment]
OK, I wasn't able to repro in Chrome, but it did repro in Firefox.

**Comment by stonebk** [comment]
Also, thank you @pt8o for the detailed bug report!

**Comment by stonebk** [comment]
Looks like it is only an issue with the vertical slider, can you confirm?

**Comment by pt8o** [comment]
@stonebk yep, only on the vertical slider.

I was able to reproduce on Chromium on Linux, I can try Chrome on Mac again tomorrow

**Comment by stonebk** [comment]
OK, the issue isn't browser related, it's related to window scrolling. If you are scrolled to the top, it works as expected, but if you scroll down, then it breaks.

Working on a fix...

**Comment by stonebk** [comment]
Published in `react-slider@1.0.2`
