### ISSUE TITLE
What is tabIndex in renderThumb props and why is it always 0?

### ISSUE THREAD

**Issue by malikiz** [zillow/react-slider#159]
I want to get thumb index. Using `key` bad for me, because I use withStyles and I do not want parse `key` to get index
https://github.com/zillow/react-slider/search?q=tabIndex&unscoped_q=tabIndex

**Comment by stonebk** [comment]
`tabIndex` is is for focus support for accessibility. Read more about it here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

If you want to get the index, you just need to get it from the state param of the render prop function:
```
renderThumb={
    (props, state) => {
        console.log('The thumb index is:', state.index);
    }
}
```

See the prop documentation for more information here:
https://zillow.github.io/react-slider/
