### ISSUE TITLE
Double call in onAfterChangeSlider method

### ISSUE THREAD

**Issue by GenisDiaz** [zillow/react-slider#161]
Hi! 

I use the onAfterChangeSlider method to do a request with the new range values and this method is called twice every time I move a thumb.

Is this the regular behavior, or I'm doing something wrong? 

thanks in advance!

**Comment by TreTuna** [comment]
I was just coming on here to report this. We use the `onAfterChange` method for analytics tracking and are now getting double reporting. I'm having to revert back our install to v0.11.2 for now until I can figure out what's going on here. What I've figured out so far is that it's getting called once after the change and then again after the slider loses focus.

**Comment by stonebk** [comment]
Looks like `onBeforeChange` is also called twice 🤔

**Comment by stonebk** [comment]
`react-slider@1.0.3`
