### ISSUE TITLE
Add documentation for the min, max, step feature

### ISSUE THREAD

**Issue by SushanRajShakya** [zillow/react-slider#164]
This feature already exists but no documentation is present.

Eg:
`<ReactSlider min={0} max={500} step={5} /> `

**Comment by stonebk** [comment]
It's documented if you click on props & methods:

https://zillow.github.io/react-slider/

<img width="398" alt="Screen Shot 2020-02-19 at 9 57 18 AM" src="https://user-images.githubusercontent.com/1432010/74860867-3bff9d80-52fe-11ea-8a39-80714f273833.png">
<img width="551" alt="Screen Shot 2020-02-19 at 9 56 29 AM" src="https://user-images.githubusercontent.com/1432010/74860817-25f1dd00-52fe-11ea-9a12-3cbbadf15760.png">
<img width="966" alt="Screen Shot 2020-02-19 at 9 56 34 AM" src="https://user-images.githubusercontent.com/1432010/74860825-28eccd80-52fe-11ea-87c9-0e62bada7096.png">
