### ISSUE TITLE
Add info that @zillowgroup/react-slider is now react-slider

### ISSUE THREAD

**Issue by hinok** [zillow/react-slider#165]
Hey,
I think it's worth to publish new version on https://www.npmjs.com/package/@zillowgroup/react-slider and updating readme and also adding specific package.json properties to inform people that package has moved from `@zillowgroup/react-slider` to `react-slider`.

**Comment by stonebk** [comment]
Good point! I'll make sure to do that, thanks!

**Comment by stonebk** [comment]
Done!

![Screen Shot 2020-04-22 at 3 04 55 PM](https://user-images.githubusercontent.com/1432010/80038518-a8d41700-84aa-11ea-9515-47d023fd5113.png)
