### ISSUE TITLE
Rewrite react-slider to TypeScript

### ISSUE THREAD

**Issue by viters** [zillow/react-slider#183]
Just an idea, but it could be worthwhile to rewrite `react-slider` in TypeScript. A lot people these days prefer TypeScript (including me), and existing types `@types/react-slider` are quite poor and insufficient.

There isn't a lot of code, so just rewriting `ReactSlider.jsx` to `tsx` should be quite easy, we can even start with just pure js in ts with only props typed.

The only thing I am concerned with is whether `create-react-styleguide` will work with `tsx` files, @stonebk you are also maintaining that repo, can you comment on this?

**Comment by stonebk** [comment]
Sorry, I don't use TS myself, so moving the project to TS is not really something I plan to do. I would encourage you to submit a PR to improve the types if TS is something you are passionate about.
