### ISSUE TITLE
Use ResizeObserver to avoid rendering issues when parent container has display: none initially

### ISSUE THREAD

**Issue by medatech** [zillow/react-slider#184]
## Description

There's been a few issues (#177, #136, #172) where if a parent element is initially hidden, it's not possible for the Slider component to calculate the widths and as such places the thumb at the far left.

I believe this is a workable solution that could be put into the component, but can be used in a project without needing to have to track parent container visibility states within the application.

## Solution

By using the `ResizeObserver` it is possible to trigger an event when the element has been made visible via a change in the CSS (e.g. display: 'block') on a parent element. This allow us to then call the `resize` method to correctly calculate the positioning.

## Code Sample

Here is a code sample of how I've managed to implement this logic. Ideally this would be moved within the component. The magic happens in the `useEffect` block.

```javascript
import React, { useRef, useEffect } from "react"
import PropTypes from "prop-types"
import styled, { css } from "styled-components"

import ReactSlider from "react-slider"

import _Track from "./Track"
import _Thumb from "./Thumb"

Slider.propTypes = {
    className: PropTypes.string.isRequired,
    min: PropTypes.number,
    max: PropTypes.number,
    value: PropTypes.number,
    onChange: PropTypes.func,
}

const Thumb = (props, state) => <_Thumb {...props}></_Thumb>
const Track = (props, state) => <_Track {...props} index={state.index} />

function Slider({ className, min = 0, max = 100, value = 100, onChange }) {
    const ref = useRef(null)
    const sliderRef = useRef(null)

    // The slider needs to be resized when a parent container becomes visible (e.g. via a display: block)
    // We'll use a ResizeObserver to detect this and check the offsetParent property on the wrapping div
    // because this will only be null if the slider is hidden
    useEffect(() => {
        if (sliderRef.current.slider === null) return

        function _handleResize() {
            // If offsetParent is null, the element is not visible
            if (sliderRef.current.slider.offsetParent !== null) {
                sliderRef.current.resize()
            }
        }

        // Observe the slider dom element which will trigger when it's shown via a parent container visibility
        const ro = new ResizeObserver(_handleResize)
        ro.observe(sliderRef.current.slider)

        // Cleanup
        return () => {
            ro.disconnect()
        }
    }, [ref.current])

    return (
        <ReactSlider
            ref={sliderRef}
            className={className}
            min={min}
            max={max}
            value={value}
            renderTrack={Track}
            renderThumb={Thumb}
            onChange={onChange}
        />
    )
}

export default styled(Slider)`
    ${(props) => css`
        width: 100%;
        height: 5px;
    `}
`
```

**Comment by stonebk** [comment]
@medatech, the documentation already has an example using `ResizeObserver` with the `resize` function:
https://zillow.github.io/react-slider/#!/ReactSlider/13

`ResizeObserver` is not supported by IE11, so I don't think I would want to build that directly into the component.
https://caniuse.com/#feat=resizeobserver

**Comment by stonebk** [comment]
Although, we could probably just feature detect and not use it in IE11 🤔

**Comment by medatech** [comment]
Thanks @stonebk. Honestly I never spotted that . I was following the conversation of the issue in the issues and would have loved to have seen that solution before I pretty much reinvented the wheel. I probably just missed it.

That said, having this work out the box would be amazing and stop other people tripping up. My use case was simple enough, everything worked perfectly, then noticed this weird thing when the parent component was moved within an accordion that was closed by default.

I'm of the opinion that feature detecting would be the ideal solution here as it means you're not letting IE dictate additional complexities in more modern browsers. With feature detection it's not going to make things worse than what you get out the box by default. The only issue may be is when people have already implemented a workaround, but even then, it probably wouldn't break things, you'd just have 2 `ResizeObserver` instances and 2 calls to the `resize` method.

**Comment by MauroTaliente** [comment]
Hi, 
solved this problem by forcing a new size adjustment.
I hope to be helpful

  // RESIZE HACK
  const sliderRef = useRef(null);
  useEffect(() => {
    if (!sliderRef.current) return;
    sliderRef.current.handleResize();
    return () => {}
  }, [sliderRef]);

    <ReactSlider
      {...{
        ref: sliderRef,
      ...

**Comment by kris-ellery** [comment]
We're adding `ResizeObserver` functionality in `v2.0.0`. See this MR https://github.com/zillow/react-slider/pull/254
