### ISSUE TITLE
How to limit slider?

### ISSUE THREAD

**Issue by istoros** [zillow/react-slider#190]
I want to limit my slider between 25 and 75 values on 0-100 line
On onChange callback I set new state, state is update, but slider value not changes (slider value not connected with my state value)
What solution of this problem?

Slider component:
`export default ({value, onChange}: any) => {
    return (
        <Slider>
            <SliderContainer>
                <StyledSlider
                    value={value}
                    onChange={onChange}
                    min={0}
                    max={100}
                />
            </SliderContainer>
        </Slider>
    )
}`

My component:
`const [value, setValue] = useState(10);
<Slider
    value={value}
    onChange={(val) => {
        setValue(Math.min(Math.max(val as number, 25), 75));
    }}
/>`

**Comment by stonebk** [comment]
Can you not just use the `min` and `max` props?

**Comment by istoros** [comment]
@stonebk I can't. I must to have 0-100 range, limited 25-75 values.
I view source code react-slider, it use personal state.
My solution is use forceUpdate. Is there another ways?
