### ISSUE TITLE
`onChange` nor `onAfterChange` gets invoked when `value` changes

### ISSUE THREAD

**Issue by coolsp** [zillow/react-slider#194]
## Description

When using `value` for controlled components and changing the linked state value the thumb gets updated however `onChange` nor `onAfterChange` gets invoked by the `ReactSlider` component. 
The expected behavior would for both `on` methods to get invoked as the value changed.

**Comment by stonebk** [comment]
This is expected behavior IMO -- a controlled `<input>` does not fire `onChange` events when you change the `value`, not sure why we would.
