### ISSUE TITLE
onChange returns old value if used with value prop

### ISSUE THREAD

**Issue by hornetDC** [zillow/react-slider#197]
## Description

Title. It worked before in 1.0.8.

## CodeSandbox

https://codesandbox.io/s/goofy-raman-znv2t

**Comment by stonebk** [comment]
Looks like a regression from https://github.com/zillow/react-slider/commit/904e927bba111820f87726ee09f4890fc4004ba9 -- looking into it.

**Comment by stonebk** [comment]
It looks like `getDerivedStateFromProps` is removing our state change before `onChange` is called with the new value.

**Comment by stonebk** [comment]
The PR needs some more thought -- going to revert the commit for now until the PR can get some more time.

**Comment by stonebk** [comment]
`react-slider@1.0.11`

**Comment by stonebk** [comment]
`react-slider@1.1.1`
