### ISSUE TITLE
onAfterChange called with old values

### ISSUE THREAD

**Issue by miromeir** [zillow/react-slider#201]
on a controlled 2-values slider, onAfterChange is getting called with old values(from before the change).

Desired Behaviour: 
onAfterChange should be passed new values, representing the slider after the change is finished (I think?)

## CodeSandbox

Try changing slider values. then, change react-slider to v1.0.11 and try again. different results.
[![Edit zillow/react-slider](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/reverent-dirac-jufsp)

**Comment by stonebk** [comment]
For now you can use `onChange` instead of `onAfterChange` and it should work.

**Comment by Jordan-Eckowitz** [comment]
> on a controlled 2-values slider, onAfterChange is getting called with old values(from before the change).
> 
> Desired Behaviour:
> onAfterChange should be passed new values, representing the slider after the change is finished (I think?)
> 
> ## CodeSandbox
> Try changing slider values. then, change react-slider to v1.0.11 and try again. different results.
> [![Edit zillow/react-slider](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/reverent-dirac-jufsp)

Having the same problem - `onAfterChange` returns the default values

**Comment by stonebk** [comment]
`react-slider@1.1.2`

**Comment by Jordan-Eckowitz** [comment]
> `react-slider@1.1.2`

Works perfectly now, thanks!

**Comment by kate-fsd** [comment]
Hi!
I sometimes have the same problem on iphone now, in controlled, 1-value component. Slider version 2.0.0
On android and desktop it works well
