### ISSUE TITLE
Get last mark at the edge of the slider

### ISSUE THREAD

**Issue by SarthakSri98** [zillow/react-slider#202]
I am trying to use the slider with 9 marks. I have set the width of the container as 100% but the last mark always come a little left side instead of at the last.
The marks array is like this:
`const marks = [ 0, 12.5, 25, 37.5, 50, 62.5, 75, 87.5, 100 ];`
<img width="315" alt="Screenshot 2020-11-28 at 7 43 04 PM" src="https://user-images.githubusercontent.com/28146914/100517655-35b62000-31b2-11eb-9870-9622c6a0a9d6.png">
If I increase or decrease the width the value of left changes accordingly and the last mark always stays a little earlier.
Please help.

**Comment by petosiso** [comment]
Hi,

how did you solve this problem? 

Thanks.
