### ISSUE TITLE
[Question] Use of `position: absolute` for marks

### ISSUE THREAD

**Issue by loichuder** [zillow/react-slider#203]
First of all, thanks for the nice package. I was happy to land on it after a few unsuccessful tries with other packages.

## Description

I tried the recently added marks and noticed an odd behaviour: **`position: absolute` must be explicitly set by the external CSS of the marks for them to be properly placed** (see image and sandbox below). 

On the other hand, tracks and thumbs do not need this as the `position: absolute` is already set by `ReactSlider` itself: https://github.com/zillow/react-slider/blob/master/src/components/ReactSlider/ReactSlider.jsx#L946 and https://github.com/zillow/react-slider/blob/master/src/components/ReactSlider/ReactSlider.jsx#L957.

Is this the expected behaviour or should `ReactSlider` set `position: absolute` for the marks as well for consistency ?

## CodeSandbox

![image](https://user-images.githubusercontent.com/42204205/101045154-5e5a6300-3580-11eb-8d7c-42e2c40a9e46.png)

[![Edit zillow/react-slider](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gifted-turing-nw9cc?file=/src/App.tsx)

**Comment by stonebk** [comment]
I agree, the inconsistency is not great. It would probably make sense to add the positioning like we do with tracks and thumbs.
