### ISSUE TITLE
Could not resolve dependency: react@16.x

### ISSUE THREAD

**Issue by deadcoder0904** [zillow/react-slider#207]
I'm trying to install `react-slider` & got the following error:

> Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.x" from react-slider@1.1.2
npm ERR! node_modules/react-slider
npm ERR!   react-slider@"*" from the root project

Can you update the peer dependency & release a new version?

https://github.com/zillow/react-slider/blob/b15be6056c621e18db50ad19dd49221da5eb3076/package.json#L43

**Comment by stonebk** [comment]
`react-slider@1.1.3`

**Comment by deadcoder0904** [comment]
Is there any way to convert it from https://github.com/tajo/react-range to this?

Here's the effect that I have when using `react-range` with the following code:

```tsx
<Range
  step={1}
  min={0}
  max={75}
  values={values}
  onChange={(values) => {
    setValues(values)
    frameItStore.updatePadding({ vertical: Number(values[0]) })
  }}
  renderTrack={({ props, children }) => (
    <div
      {...props}
      className="w-full h-3 pr-2 my-4 ml-2 bg-gray-200 rounded-md"
    >
      {children}
    </div>
  )}
  renderThumb={({ props }) => (
    <div
      {...props}
      className="w-5 h-5 bg-indigo-500 rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
    />
  )}
/>
```

![react-range](https://user-images.githubusercontent.com/16436270/105491500-614e1600-5cdc-11eb-9442-65d0c75c5bf0.png)

I tried converting reading the docs like:

```tsx
<ReactSlider
  step={1}
  min={0}
  max={75}
  className="horizontal-slider"
  thumbClassName="w-5 h-5 bg-indigo-500 rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
  trackClassName="w-full h-3 pr-2 my-4 ml-2 bg-gray-200 rounded-md"
  value={values}
  onChange={(values: any) => {
    setValues(values)
    frameItStore.updatePadding({ vertical: Number(values[0]) })
  }}
/>
```

But it's showing only little thumb & cuts-off (see `Vertical`):

![react-slider](https://user-images.githubusercontent.com/16436270/105491827-fe10b380-5cdc-11eb-9683-60fa8a3d30f1.png)

Any clues what I'm doing wrong?

**Comment by deadcoder0904** [comment]
Okay, I made it work with minute changes however the position of the thumb was a little off which I fixed by adding `absolute -top-1`:

```tsx
<ReactSlider
	step={1}
	min={0}
	max={75}
	className="w-full h-3 pr-2 my-4 bg-gray-200 rounded-md"
	thumbClassName="w-5 h-5 bg-indigo-500 rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 absolute -top-1"
	value={value}
	onChange={(value: any) => {
		console.log(value)
		setValue(value)
		frameItStore.updatePadding({ vertical: Number(value) })
	}}
/>
```

![range](https://user-images.githubusercontent.com/16436270/105494081-4aa9be00-5ce0-11eb-9f9e-79afad2fc2a5.png)

Not sure if the thumb position is intended like that but hey it works. Thanks for this library :)
