### ISSUE TITLE
how can i update the slider value when the zoom has been updated by others 

### ISSUE THREAD

**Issue by MarvenGong** [zillow/react-slider#220]
## Description

Please provide a brief description of the issue including what you are seeing as well as the expected behavior.

## CodeSandbox

Please provide a CodeSandbox that clearly reproduces the issue. **Issues without a CodeSandbox are less likely to get resolved quickly.**

[![Edit zillow/react-slider](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zillowreact-slider-l3vuc?fontsize=14&hidenavigation=1&theme=dark)

**Comment by stonebk** [comment]
If you go to the [documentation](https://zillow.github.io/react-slider/), there is an example that shows you how to programmatically resize the slider.

![Screen Shot 2021-05-18 at 2 44 25 PM](https://user-images.githubusercontent.com/1432010/118727515-b8c24580-b7e7-11eb-9482-bde461ce0672.png)
