### ISSUE TITLE
Thumb position gap

### ISSUE THREAD

**Issue by SofiaGR** [zillow/react-slider#242]
Hello,

I really like this slider and how it is accessible and CSS agnostic, however there is one _tiny_ thing that I wonder if something can be done about it.

I created a sandbox to explain it: https://codesandbox.io/s/festive-shannon-swbmg?file=/src/App.tsx

Is it possible to fix this gap between the track and the thumb? It's literally 1px 😓 
<img width="301" alt="Screenshot 2021-11-03 at 15 35 28" src="https://user-images.githubusercontent.com/1965262/140092457-18fe64c8-0a4a-45d2-a264-3469426a1882.png">

**Comment by stonebk** [comment]
The gap is a result of the border radius on the thumb. If you remove the border radius, you'll no longer see any gap:

<img width="713" alt="Screen Shot 2021-12-21 at 1 25 22 PM" src="https://user-images.githubusercontent.com/1432010/146999754-f5172a06-6d54-4c8d-ac52-3d77bccebab6.png">

If you want to remove the gap, you can make the thumb larger and offset it to cover the gap.
