### ISSUE TITLE
Jump to position

### ISSUE THREAD

**Issue by mrakjos** [zillow/react-slider#26]
I have sliders with same settings:
            min: -1,
            max: 1,
            step: 0.01,
            withBars: true,

When I click on 'label 2' to position 0, handlebar jump to position on right side of cursor:

![screen shot 2015-03-09 at 11 15 17](https://cloud.githubusercontent.com/assets/7734088/6553365/463ffc94-c650-11e4-8f72-a592495dbee9.png)

After I zoom in/out web page jump to position works fine :)

![screen shot 2015-03-09 at 11 15 26](https://cloud.githubusercontent.com/assets/7734088/6553425/e152eea8-c650-11e4-84b2-f4a690d0330e.png)

I have problem on Yosemite OS X with Chrome, Firefox, Safari and IE11 on virtual. On Safari "zoom patch" don't work.

Jakub.

**Comment by mrakjos** [comment]
It is good after update to 0.5.1. Thanks

**Comment by qwtel** [comment]
Thanks for keeping the issue up to date :)
