### ISSUE TITLE
Slider thumb snaps back when ending touch event

### ISSUE THREAD

**Issue by njdancer** [zillow/react-slider#279]
## Description

When ending a touch event on mobile, sometimes the thumb will snap back to a previous value.

## CodeSandbox

This can be reproduced on the documentation page at [https://zillow.github.io/react-slider/](https://zillow.github.io/react-slider/), specifically on the Slider with marks. It is intermittent however and only occurs on mobile.

**Comment by kris-ellery** [comment]
Thank you for your patience. Merged and published in v2.0.5
