### ISSUE TITLE
[ERROR] Could not resolve "@babel/runtime/helpers/extends"

### ISSUE THREAD

**Issue by YYsuni** [zillow/react-slider#284]
## Description

ReactSlider doesn't work in the Vite TS project.

![image](https://user-images.githubusercontent.com/53907086/217414644-9eff231c-44ab-4862-8ff2-2f89e482194d.png)

## CodeSandbox

[![Edit zillow/react-slider](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/naughty-tdd-cl8y17?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A29%2C%22endLineNumber%22%3A20%2C%22startColumn%22%3A29%2C%22startLineNumber%22%3A20%7D%5D)

**Comment by kris-ellery** [comment]
You might need to install `@babel/runtime` as dev dependency.

**Comment by YYsuni** [comment]
It works! Thank you👍🏻
