### ISSUE TITLE
inverted slider keyDown goes the wrong way.

### ISSUE THREAD

**Issue by andrew-gross** [zillow/react-slider#286]
## Description

I saw a previously closed ticket from years ago that was resolved for when a slider was inverted the key changes were going in the wrong direction. This still seems to be a problem when the slider is NOT vertical, but is just in the standard horizontal orientation. Let me know if the example doesn't work. I've grabbed the most recent version

## CodeSandbox

https://codesandbox.io/s/romantic-banzai-y4lhvs?file=/src/App.js

**Comment by kris-ellery** [comment]
Thank you for your patience. Merged and published in v2.0.5
