### ISSUE TITLE
onAfterChange callback is never fired

### ISSUE THREAD

**Issue by bitfella** [zillow/react-slider#3]
Hello, unfortunately I can't make onAfterChange callback work. It never fires.
Perhaps I am doing something wrong? Documentation isn't very explanatory.

See this codesandbox for a (not) working example: https://codesandbox.io/s/charming-edison-b9l7v

Thanks

**Comment by stonebk** [comment]
Sorry, for some reason notifications were not enabled on this repo for me. This is a bug that was pointed out in a PR as well. I'll try to get a fix ASAP!

**Comment by stonebk** [comment]
`@zillowgroup/react-slider@2.0.1`
