### ISSUE TITLE
RequireJS issues

### ISSUE THREAD

**Issue by basharov** [zillow/react-slider#31]
When I include react-slider into my RequireJS config, it throws this:

![image](https://cloud.githubusercontent.com/assets/625090/7449896/233031d8-f247-11e4-8b77-b8185ae50852.png)

But when I remove it, all works fine without this library. What can lead to this error?

**Comment by qwtel** [comment]
The component uses Universal Module Definition (good explanation [here](http://davidbcalhoun.com/2014/what-is-amd-commonjs-and-umd/)). The relevant code is right at the beginning: 

``` js
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['react'], factory);
  } else if (typeof exports === 'object') {
    module.exports = factory(require('react'));
  } else {
    root.ReactSlider = factory(root.React);
  }
}(this, function (React) {
```

It assumes that you have defined an alias (not sure what the exact requirejs term is) for the name `"react"` that maps to a specific location.
