### ISSUE TITLE
Drag Doesn't Work on Chrome on Ubuntu 14.04

### ISSUE THREAD

**Issue by BDiehr** [zillow/react-slider#35]
This sounds like it's more likely a chrome issue, but I have Ubuntu 14.04 installed through VirtualBox, and the sliders do not work on chrome. They however, did work on firefox, as well as chrome on my Windows host computer.

Any thoughts on this?

Thanks!

**Comment by BDiehr** [comment]
Can we safely declare this repo dead?

**Comment by qwtel** [comment]
No, I just work on it very inconsistently.

**Comment by dmitry** [comment]
@BDiehr for me it works at least for 1.04 and 1.05 on chrome 43 and 44 in linux (Mint).

**Comment by kumarharsh** [comment]
I've tested it on Chrome, and it works perfectly.

Chrome: Version 44.0.2403.157 (64-bit)
Ubuntu: 14.04

**Comment by imbrianj** [comment]
This works for me in Chromium on 16.04.  Can we safely declare this issue dead?

**Comment by mpowaga** [comment]
@BDiehr Closing due to age of this issue. Feel free to reopen if it still doesn't work.
