### ISSUE TITLE
Reset Value?

### ISSUE THREAD

**Issue by timarney** [zillow/react-slider#42]
Is there a way to reset the value of the slider?  There seems to be an issue if I'm dynamically swapping out the min max values - see https://github.com/timarney/react-slider

Roughly this:

``` js
click:function(val){
        if(val === 'night'){
           this.setState({min:1,max:200});
        }else{
            this.setState({min:2000,max:4000});
        }
}

slider = Demo({
            min:this.state.min,
            max:this.state.max,
            defaultValue: [this.state.min],
            orientation: 'horizontal',
            withBars: true
            });
```

The min and max update but the value is messed up until you interact with the slider again... in which case the slider corrects itself.  

If there was a way to reset to the default value I'm thinking that would work.

**Comment by timarney** [comment]
I modified my setup to use the slider as a controlled component ... that seems to do the trick.

**Comment by qwtel** [comment]
This is intended behaviour. However there might be problems with controlled components as well. Feel free to open a new issue if you run into any.

btw: in your example you are not passing `this.state.max` to the component
