### ISSUE TITLE
Problem with getting slider's length

### ISSUE THREAD

**Issue by durkiewicz** [zillow/react-slider#44]
The slider doesn't behave correctly when it's contained in an element that expands on some user action. By "expands" I mean a transition that involves `transform: scale(...)` CSS property.

This issue is a bit similar to this: https://github.com/mpowaga/react-slider/issues/15 because the root cause of the issue is that the size in component's state is not up to date.

**Comment by electerious** [comment]
Experiencing the same problem. My slider is inside a transformed div (`transform: translateX(-100%)`). Clicking the slider sets the handler to the wrong position. I think that the position calculation of clicks is incorrect because of `transform`.
