### ISSUE TITLE
Values return problem

### ISSUE THREAD

**Issue by ghost** [zillow/react-slider#48]
Hey,

I like your work and product (slider) very much. Unfortunately I have stumbled upon a problem with returning values. I can't figure down, basing on source file, how to do it correctly (2 values), so there will be 2 correct values returned. 

All best,
Pszek

**Comment by qwtel** [comment]
Hi, thank you. I'm not sure if I know what you mean. Could you write some code that shows what you're expecting?

**Comment by Pszek** [comment]
Hey,

Thank You for quick response. Sorry for my late one; I am just learning REact and Flux, so sometimes I don't see obvious mistakes. Could You recommend me some good learning resources (or a pathway).

With Regards,
Pszek


maciej.ciniewski@student.wat.edu.pl
 
From: Florian Klampfer
Date: 2015-08-26 22:38
To: mpowaga/react-slider
CC: 齐涅夫斯基 马泰伊 
Subject: Re: [react-slider] Values return problem (#48)
Hi, thank you. I'm not sure if I know what you mean. Could you write some code that shows what you're expecting?
—
Reply to this email directly or view it on GitHub.
--> --> 
-->
