### ISSUE TITLE
Warning when using React 0.14

### ISSUE THREAD

**Issue by hugihlynsson** [zillow/react-slider#51]
When using react-slider in a React 0.14 project, the following warning is issued by React:

> ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `ReactSlider`

**Comment by qwtel** [comment]
Ah, thank you for trying the component with react 0.14.

I've heard of this change, but I don't know how to best handle it, so that the component can be used with react 0.13 and 0.14.
Checking for `getDOMNode` to be defined seems like a pretty brute way to do it :/ 
Happy to receive any input concerning this.

**Comment by hugihlynsson** [comment]
Yeah, I'm not sure either what is the best way to go forward with this, without breaking backwards comparability. In React 0.14, this is only a warning, so maybe is should just stay like it is until it will be totally deprecated.

**Comment by qwtel** [comment]
Now would be the time to fix the warning so the component doesn't break when it is totally deprecated. 
I assume there will be a suggested way of handling this once 0.14 is released. Or we just add the check...

**Comment by canfie1d** [comment]
I think `.findDOMNode()` replaces it, no?
http://www.omerwazir.com/posts/react-getdomnode-replaced-with-findDOMNode/

**Comment by hugihlynsson** [comment]
@canfie1d That change was introduced in React 0.13, but 0.14 includes further changes. `findDOMNode()` is no longer a part of the react package, but rather a new react-dom package. Also, refs that point to a DOM component now _are_ the DOM node, and should not be wrapped with `findDOMNode()`. See more here in the [React 0.14 blog post](https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html)

**Comment by canfie1d** [comment]
Ah- I see. Thanks for that.

**Comment by dmitry** [comment]
Looks like the right way to release new version of a package with strict dependency to react 0.14.

PS. Similar idea: https://github.com/moroshko/react-autosuggest/commit/4ab699dc20114c2287e24ace3129da4ddfb4f04b

**Comment by qwtel** [comment]
Thanks for looking it up :+1:

**Comment by martpie** [comment]
Any news on that ? react 0.14 is out now.

Instead of findDOMNode, just use refs:

```
render() {
    return <div ref='element'></div>;
}

doSomething() {
    console.log(this.refs.element); // will print the node element to the console
}
```

**Comment by nuclearspike** [comment]
I too am looking forward to .14 support.

**Comment by nuclearspike** [comment]
The warning stops happening if you just remove the ".findDOMNode()" from 2 places in the code.

**Comment by martpie** [comment]
I submitted a PR for that, but the maintainer seems inactive.

**Comment by gabssnake** [comment]
@KeitIG your PR doesn’t seem to update package.json or handle compatibility with 0.13

**Comment by martpie** [comment]
True dat, doing it asap.

**Comment by martpie** [comment]
Done.

**Comment by mauricesvay** [comment]
:+1:

**Comment by Martindelataille** [comment]
Waiting fix too. @KeitIG  Thanks

**Comment by martpie** [comment]
@Martindelataille, yep, would be great if the PR was accepted now :)

**Comment by martpie** [comment]
Issue can be closed now a new version is released. poke @hugihlynsson

**Comment by hugihlynsson** [comment]
Super!
