### ISSUE TITLE
Issue Implementing

### ISSUE THREAD

**Issue by alexmugford** [zillow/react-slider#54]
Hello,

I think this is just my issue, and not a real issue.  I'm trying to put this into my react program by doing the following:

var React = require('react');
var MultiSlider = require('react-slider');

var myClass = React.createClass({

```
render: function () {

    return (
            <MultiSlider defaultValues={[8, 1]} />
    );
}
```

});

module.exports = myClass ;

When I run it, nothing appears on screen, but it shows up in the developer tools.  The div with class "class='slider'" has a height of 0px.  I'm not sure where I'm going wrong...I'm sure it's just a silly mistake on my end!

Thanks in advance,
Alex

**Comment by qwtel** [comment]
Hm, couple of things:
- the slider comes without a default styling, so you have to define your own. Start with the CSS from the example, and work towards what you want it to look like.
- it's `defaultValue`, not `defaultValues` (to be in line with other react input elements)
- the values you provide must be sorted ascending, so it should be defaultValue={[1, 8]}
- at the very least you should define `min` and `max` values, like you would with a `<input type="range"/>`.

**Comment by alexmugford** [comment]
Great, thanks for the input!

I had another class name 'slider' which seemed to have been conflicting with it.  I can see the component now after giving it a new className through the props!

Thanks for the quick reply, and thanks for this component!
