### ISSUE TITLE
Changing # of children causes prop discrepency.

### ISSUE THREAD

**Issue by YourDeveloperFriend** [zillow/react-slider#59]
This bug is apparent when you use both `value` and children. Example:

``` javascript
render: function() {
  return <ReactSlider withBars={true} value={this.state.value}>
    {this.state.labels.map(function(label) { return <div>{label}</div>; })}
  </ReactSlider>
}
```

If you add a value to both `value` and `labels`, neither display in the react slider. Here's a [jsfiddle demonstrating the bug](https://jsfiddle.net/g11cup6g/1/). The offending code is in the [`_or` function](https://github.com/mpowaga/react-slider/blob/v0.6.0/react-slider.js#L245), which relies on `this.props.children`, but doesn't pull the new children from the updated props in `componentWillReceiveProps`. Here's that [same jsfiddle, with a fix](https://jsfiddle.net/e3e32o8k/1/), which I will include in a PR.

**Comment by vinayakpatil** [comment]
Why is this not merged yet? I am facing the same issue. I also have the similar fix.

**Comment by vinayakpatil** [comment]
@mpowaga Any update on this PR? I still see this issue, thanks!

**Comment by gregtalarico** [comment]
+1
