### ISSUE TITLE
Handles are not updated when using controlled component

### ISSUE THREAD

**Issue by cedricmessiant** [zillow/react-slider#65]
I am using react-slider with redux. Handles are not updated when we pass a new value to ReactSlider component

**Comment by albertogasparin** [comment]
+1

**Comment by pbruijnes** [comment]
+1

**Comment by maslianok** [comment]
the same

**Comment by xiaolin** [comment]
+1

**Comment by klase** [comment]
+1

**Comment by mauricio-gamboa** [comment]
+1

**Comment by jvdhoeven** [comment]
Current version v0.6.1 has a "value" attribute for controlled components

> **value {oneOfType([number, arrayOf(number)])} default: 0**
> Like defaultValue but for controlled components.

When i change the state of value it changes the corresponding handles.
