### ISSUE TITLE
broken out of the box?

### ISSUE THREAD

**Issue by foodaka** [zillow/react-slider#69]
Is there something im doing wrong? the component wont render

import React from 'react';
import ReactDOM from 'react-dom';
import ReactSlider from 'react-slider';

const DepthMeterInput = React.createClass({

  render() {
    return (
      <div>
        <ReactSlider defaultValue={50} />
        blahahh
      </div>
    );
  }
})

export default DepthMeterInput

**Comment by foodaka** [comment]
i dont know why but it doesnt show my return

```
  <div>
    <ReactSlider defaultValue={50} />
    blahahh
  </div>
```

**Comment by istrel** [comment]
@foodaka For now react slider is a non-es6 module, so you should use CommonJS `require` call or import this with `*` like this:

```
import React from 'react';
import ReactDOM from 'react-dom';
import * as ReactSlider  from 'react-slider';

const DepthMeterInput = React.createClass({
  render() {
    <div>
      <ReactSlider defaultValue={50} />
      blahahh
    </div>
  }
})

export default DepthMeterInput;
```

**Comment by kunokdev** [comment]
@foodaka it seems that it doesn't work even with your workaround?

**Comment by VanDavv** [comment]
@foodaka @istrel this issue is still present, workaround doesn't word, should be reopened!

**Comment by istrel** [comment]
@VanDavv DId you try to use CommonJS require? It should work with webpack:
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
const ReactSlider = require('react-slider');

const DepthMeterInput = React.createClass({
  render() {
    <div>
      <ReactSlider defaultValue={50} />
      blahahh
    </div>
  }
})

export default DepthMeterInput;
```

**Comment by VanDavv** [comment]
Yes, and I still didn't manage to see the slider. Sorry, but i ended up using `rc-slider`

**Comment by sckoh** [comment]
im unable to see the slider too

**Comment by nigelrobbins3** [comment]
The slider is hidden by default. The divs are there with the right classes, but without CSS rules they are empty. Hopefully it's just a matter of adding the CSS you want.
