### ISSUE TITLE
Can't open index.html demo

### ISSUE THREAD

**Issue by tp** [zillow/react-slider#70]
When opening the demo index.html it fails with this error:

```
(index):98 Uncaught TypeError: React.initializeTouchEvents is not a function
```

commit: 63eb81ed11d1d9f7bad16736dce0885c3d5fb9fa

Browsers:
- Firefox 45.0a2 (2016-01-25) (OS X)
- Chrome 50.0.2630.0 canary (64-bit) (OS X)

```
=> npm ls
react-slider@0.6.1 /Users/timm/Projects/react-slider/react-slider
└── react@0.14.0
```

```
=> npm -v
3.5.3
```

**Comment by mpowaga** [comment]
Version 0.8.0 fixes the problem. If you are opening index.html from your local machine you must `npm install react react-dom create-react-class prop-types` first.
