### ISSUE TITLE
React v15.0.0

### ISSUE THREAD

**Issue by xiaolin** [zillow/react-slider#74]
Hi guys,

When updating react to the newly releases v15.0 I'm getting this npm error:

`peerinvalid Peer react-slider@0.6.1 wants react@>=0.14`
Any chance you can bump the dependency to allow v15.0?

Thanks!

**Comment by jamesbrauman** [comment]
@xiaolin 

The peer dependency for `react-slider` has been added in the new release `0.7.0`. Could you please confirm that this has resolved your issue?

**Comment by jamesbrauman** [comment]
@xiaolin This issue has been resolved in the latest release `0.7.0`.

**Comment by xiaolin** [comment]
@jamesbrauman thanks!
