### ISSUE TITLE
How can i use this compoenent in my exiting React Page???

### ISSUE THREAD

**Issue by nishvs** [zillow/react-slider#79]
How can i use this compoenent in my exiting React Page???

I already have a <div> where i am rendering the React compoenent. In that compoenent i need a slider slider component. How can i use this component??

**Comment by jamesbrauman** [comment]
@nishvs 

There are instructions in the `README.md` file for implementing this component into your page, and the [source code for the demo](https://github.com/mpowaga/react-slider/blob/master/index.html) has an example implementation.
