### ISSUE TITLE
Custom Class Names with CSS Modules

### ISSUE THREAD

**Issue by jacobp100** [zillow/react-slider#81]
For the barClassName, you set the class to something like `bar bar-1`.

However, when using CSS Modules, it is impossible to target `.bar-1`, since the class names generated from `bar` and `bar-1` are completely separate, and have no relation to each other.

Maybe a solution would be to allow barClassName to take an array of names to use.

**Comment by jamesbrauman** [comment]
@jacobp100 Any chance you could submit an example pull request that shows how you would like this work?

**Comment by ghost** [comment]
put :global infront of your class and it will work
