### ISSUE TITLE
Project alive? There are many PRs to merge!

### ISSUE THREAD

**Issue by simoneb** [zillow/react-slider#86]
Hey,

this component is really useful but it has quite some bugs, which several of the PRs fix.

Any chance to have them included in this repo?

**Comment by LoicUV** [comment]
ping @mpowaga

**Comment by jamesbrauman** [comment]
I emailed @mpowaga he replied once, but then not again. I offered to help merge some of the pull requests.

**Comment by thepapanoob** [comment]
im going to fork it and merge all PR's as this repo seems abandond

**Comment by simoneb** [comment]
excellent initiative @Kruemmelmonster. Can you post a link to the repo when you do it?

**Comment by joshwcomeau** [comment]
@Kruemmelmonster please share.

@mpowaga can you please mark this package as deprecated? Nothing more frustrating than spending the time to familiarize and integrate a solution, only to realize that it's unusable because the owner has abandoned it.

**Comment by thepapanoob** [comment]
@simoneb & @joshwcomeau as im not the owner i have to do it manually but im right at the middle of doing it

**Comment by petyappetrov** [comment]
Where author... 😢

**Comment by jamesbrauman** [comment]
@Kruemmelmonster @petyappetrov @joshwcomeau 

I've been given collaborator access to the repository by the owner. I will merge some pull requests.

**Comment by jamesbrauman** [comment]
@simoneb @LoicUV @Kruemmelmonster @petyappetrov 

I have published a new minor version, which contains support for `react ^15.0.0`. Expect to see more updates soon in the future.

**Comment by joshwcomeau** [comment]
Yay! Thanks @jamesbrauman
