### ISSUE TITLE
Use of Legacy String Ref API

### ISSUE THREAD

**Issue by Mike-Bell** [zillow/react-slider#98]
Code has 2 uses of `this.refs` and the "legacy string ref API"

```
ref: 'slider'
ref: 'handle' + i

var slider = this.refs.slider;
var handle = this.refs.handle0;
```

According to [relevant React docs](https://facebook.github.io/react/docs/refs-and-the-dom.html#legacy-api-string-refs), "string refs have some issues, are considered legacy, and are likely to be removed in one of the future releases".

**Comment by not-mike-smith** [comment]
I saw this and it caused the code not to work in my environment.  I read through the link you posted and changed the code in a fork.  I'm new to both open source and front end coding, but my fix is [available here](https://github.com/smithmb-code/react-slider/commit/846aaf6b62e559dc49076211603b2d9e92b43264) for review

**Comment by Mike-Bell** [comment]
that looks about right to me. Are you using React 16? wonder if they finally remove string refs there.

**Comment by not-mike-smith** [comment]
I'm using React 15.6.2, actually.  Should I make a pull request?  Thanks
